### ISSUE TITLE
How do you find my Portfolio? 

### ISSUE THREAD

**Issue by PolinaStamenova** [PolinaStamenova/Portfolio#10]
Hello everyone, does someone has an idea what can I change to improve it ?

**Comment by TouringIdk** [comment]
It's looking good, but you are using more than one h1 after line 49, you are repeating it on the line 90, 109, 129, 151, 173

that is a issue for a person with visual disabilities that's depends on special devices to read web information,i kindly suggest to you to change them with h2, they can be repeated

**Comment by Munsa1** [comment]
Hi great job so far, at the moment there is nothing to change, keep up the good work😉

**Comment by NJ-2020** [comment]
Hi there,

In your banner, the paragraph brokes when I use it for the laptop screen.

Well done.
