### ISSUE TITLE
What to change?

### ISSUE THREAD

**Issue by PolinaStamenova** [PolinaStamenova/Portfolio#6]
Hello everyone, could you please help me to improve my PR?

**Comment by TouringIdk** [comment]
Try downloading the background for the desktop version from Figma.

**Comment by vladanvi99** [comment]
In works section, you can wrap the image with some div like class="card-image" and other content you can wrap in second div, something like class="card-info", and then later you can easier manipulate with these two elements.

**Comment by PolinaStamenova** [comment]
Thank you a lot!
